attributes/default.rb
metadata.rb
providers/compile.rb
providers/install.rb
recipes/default.rb
recipes/install.rb
templates/default/configure-no-expect-with-gpu.sh.erb
templates/default/configure-no-expect.sh.erb

Upgraded to tensorflow 1.2.
Added support for:
* src or distribution installations 
* building with support for infiniband (tensorflow-on-spark)
* building with support for MPI (ring-AllReduce by Baidu)
* building with support for Intel MKI (better performance for CPU matrix ops)

Upgrade to 1.2

---

providers/install.rb

Fix download url for Tf with GPU support

HOPSWORKS-104

---

providers/compile.rb
templates/default/configure-no-expect-with-gpu.sh.erb
templates/default/configure-no-expect.sh.erb

Pin down to a specific version of Tf
https://hopshadoop.atlassian.net/browse/HOPSWORKS-111

HOPSWORKS-111

---

attributes/default.rb
recipes/default.rb

Add files for Mnist tour of Hopsworks

Hopsworks 99

---

providers/compile.rb

Recommended Open MPI version is 3 with Horovod

Update to openmpi3

---

attributes/default.rb
recipes/default.rb
recipes/install.rb

https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-468

[HOPSWORKS-468] Kagent restart, performance impact assessment 

---

recipes/serving.rb

https://hopshadoop.atlassian.net/browse/HOPSWORKS-555

[HOPSWORKS-555] Upgrade support

---

attributes/default.rb
metadata.rb
providers/compile.rb
recipes/default.rb

https://hopshadoop.atlassian.net/browse/HOPSWORKS-578

[HOPSWORKS-578]  install custom tensorflow binaries

---

recipes/default.rb

Testing: https://github.com/hopshadoop/hops-testing/pull/112

[HOPSWORKS-594] Fix compilation bug in tensorflow::default

---

attributes/default.rb
recipes/default.rb

Testing: https://github.com/hopshadoop/hops-testing/pull/120

[HOPSWORKS-608} Put back the code for downloading hops-tensorflow.jar

---

recipes/install.rb

https://hopshadoop.atlassian.net/browse/HOPSWORKS-636

[HOPSWORKS-636] only install nccl2 if cuda_download_terms/accept is 'true'

---

attributes/default.rb
metadata.rb
recipes/default.rb
recipes/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-638

[HOPSWORKS-638} Upgrade to tf 1.10 

---

attributes/default.rb
recipes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-648

[HOPSWORKS-648] Remove hard-coded python versions

---

recipes/default.rb

pyjks is a dependency in hops-util-py for the new Kafka module

[HOPSWORKS-699] add pyjks to conda environment

---

.gitignore
attributes/default.rb
metadata.rb
recipes/default.rb

- Download feature store tour artifacts
- Move feature store tour artifacts to HDFS

[HOPSWORKS-853] Feature Store Tour

---

recipes/default.rb

- Add petastorm to base environment

[HOPSWORKS-852] Add support for petastorm

---

providers/install.rb
recipes/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-926

[HOPSWORKS-926] Stringify rhel/epel attribute

---

attributes/default.rb
metadata.rb
providers/amd.rb
providers/install.rb
providers/purge.rb
recipes/default.rb
recipes/install.rb
resources/amd.rb

[HOPSWORKS-1052] Upgrading ROCm, ROCm support CentOS, Pydoop upgrade, dropping base environments when rerunning default recipe

---

attributes/default.rb
recipes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1089

[HOPSWORKS-1089] Integration of sparkmagic with maggy

---

recipes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1096

[HOPSWORKS-1096] Add support for what-if tool (witwidget)

---

recipes/default.rb

- Install flask and sci-kit learn in project envs so that we can serve
models from there

[HOPSWORKS-751] support sklearn model serving

---

recipes/default.rb

[HOPSWORKS-1104][featurestore] visualization of feature stats

---

attributes/default.rb
metadata.rb
providers/install.rb
recipes/default.rb

https://github.com/logicalclocks/hops-testing/pull/433

[HOPSWORKS-1145] Upgrade to TF 1.14, Cuda10, Cudnn7.6, Pydoop2.0.0

---

attributes/default.rb
metadata.rb
recipes/default.rb
recipes/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1243

[HOPSWORKS-1243] Install jupyter-git-commands plugin when doing EE installation

---

attributes/default.rb
metadata.rb
recipes/default.rb
recipes/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1208

[HOPSWORKS-1208] JupyerLab

---

recipes/default.rb

Fix installation order of witwidget and export LD_LIBRARY_PATH when installing TensorFlow model analysis with ROCm

[HOPSWORKS-1208] Fix witwidget installation order

---

attributes/default.rb
recipes/default.rb
recipes/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1418
Bump pytorch, numpy versions.

[HOPSWORKS-1418] Pytorch 1 3

---

attributes/default.rb
recipes/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1511

[HOPSWORKS-1511][HOPSWORKS-1540] PyTorch upgrade to 1.4 and PCI tool fix on ubuntu

---

metadata.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1676

[HOPSWORKS-1676] Expose maggy version in Chef

---

attributes/default.rb
recipes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1689

[HOPSWORKS-1689] Make maggy installable by git URL

---

providers/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1727

[HOPSWORKS-1727] S3 URL to nccl binaries broken

---

recipes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1836

[HOPSWORKS-1836] Pin nbdime-jupyterlab version

---

recipes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1836

[HOPSWORKS-1836] Pip nbdime-jupyterlab version

---

recipes/default.rb

Reverts logicalclocks/tensorflow-chef#128

Revert "[HOPSWORKS-1836] Pin nbdime-jupyterlab version"

---

recipes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1836

[HOPSWORKS-1836] Fix nbdime version after installing jupyterlab/git

---

attributes/default.rb
providers/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2047

[HOPSWORKS-2047] upgrade nvidia version

---

recipes/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2405

[HOPSWORKS-2405] Change to python3
